/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-113111-g4fee63b241-20231227"
#endif /* AVUTIL_FFVERSION_H */
